/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ASpace: typeof import("@arco-design/web-vue")["Space"];
    ColorPalette: typeof import("./components/ColorPalette.vue")["default"];
    ColorPaletteGroup: typeof import("./components/ColorPaletteGroup.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
